apiVersion: v1
kind: Pod 
metadata:
  name: api-service 
spec:
   containers:
    - name: api-service 
      image: api-service:1.0.0
      imagePullPolicy: Never
      ports:
      - containerPort: 3000